FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Install only production dependencies
RUN npm ci --omit=dev

COPY . .

# Set Node environment to production
ENV NODE_ENV=production

EXPOSE 5000

CMD ["npm", "start"]
